version: '3.7'

services:

  frontend:
    container_name: vue_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - './node_modules:/app/node_modules'
    ports:
      - '8081:8080'
    environment:
      - CHOKIDAR_USEPOLLING=true
